version: '3.5'
services:
  vejrapi:
    build: .
    container_name: vejrapi
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - front-facing
    
  redis:
    image: redis:alpine
    container_name: vejr-redis
    restart: unless-stopped

networks:
  front-facing:
    external: true
    name: proxy