# version: '3'
version: '2' 
services:
  api:
    build:
      context: .
      dockerfile: server.Dockerfile
    image: frbsc/vejr:server
    ports:
      - "4455:5000"
    depends_on:
      - redis
    
  redis:
    image: redis:alpine
    container_name: vejr-redis
    expose: ["6379"]
